### ISSUE TITLE
Can you add these guys to HS Hackers?

### ISSUE THREAD

**Issue by jonleung** [hackedu/club-in-a-box#11]
5/6 of them joined the HS Hackers FB Group:

Sean Fronteras
Eric Hon
Dawson Wu
Michelangelo Barbic
Miguel Hernandez
Justin Yee

**Comment by zachlatta** [comment]
Added the following, anyone not added has already been accepted or hasn't requested to be added to the group yet:

* Eric Hon
* Miguel Hernandez
* Justin Yee
