### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by zachlatta** [hackedu/club-in-a-box#5]
Create a timeline from now, April 2015, to August 2015 (initial iteration) for the club in a box.

* [ ] Find out what effective timelines for projects look like
* [ ] ???
* [ ] Profit (Orpheus)

**Comment by jonleung** [comment]
Preliminary Work hackedu/club-in-a-box/issues#31c51cc9

**Comment by jonleung** [comment]
Added preliminary timeline for club in a box, next steps
(1) Peer Review
(2) Identify Riskiest Assumptions

https://github.com/hackedu/club-in-a-box/blob/master/timeline/timeline.md

**Comment by zachlatta** [comment]
FYI:

1. You can link to specific commits (so the link is immutable, file paths can change) directly by putting the commit SHA like `8a99234f7296cce90e4e5990ace3e5156bcf8095` 8a99234f7296cce90e4e5990ace3e5156bcf8095
2. If LibreOffice files are saved in their flat XML format (`.fods` for Calc) then git can version control the file itself, instead of just store binary copies. I'm going to go ahead and save `Timeline.ods` as `timeline.fods`.
