### ISSUE TITLE
Plan Lowell club meeting

### ISSUE THREAD

**Issue by zachlatta** [hackedu/club-in-a-box#6]
Perhaps this should go into https://github.com/hackedu/docs.

* [x] Create meeting agenda
* [ ] Create post-meeting survey

@jonleung, @MaxWofford

**Comment by MaxWofford** [comment]
I will create a single form that we can use for all meetings, and have a subdomain (ex. feedback.hackedu.us) route to it.

**Comment by MaxWofford** [comment]
Forgot to pass out post-meeting survey.
